# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import control_pb2 as control__pb2


class DirectoryServerStub(object):
    """定义目录服务器的控制接口
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RequestTunnel = channel.unary_unary(
                '/DirectoryServer/RequestTunnel',
                request_serializer=control__pb2.TunnelReq.SerializeToString,
                response_deserializer=control__pb2.TunnelResp.FromString,
                )


class DirectoryServerServicer(object):
    """定义目录服务器的控制接口
    """

    def RequestTunnel(self, request, context):
        """SMR 发起随遇接入请求，申请建立隐匿隧道
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DirectoryServerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RequestTunnel': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestTunnel,
                    request_deserializer=control__pb2.TunnelReq.FromString,
                    response_serializer=control__pb2.TunnelResp.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'DirectoryServer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DirectoryServer(object):
    """定义目录服务器的控制接口
    """

    @staticmethod
    def RequestTunnel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/DirectoryServer/RequestTunnel',
            control__pb2.TunnelReq.SerializeToString,
            control__pb2.TunnelResp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
