# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: control.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rcontrol.proto\"I\n\tTunnelReq\x12\x0e\n\x06smr_id\x18\x01 \x01(\t\x12\x15\n\rtarget_sar_ip\x18\x02 \x01(\t\x12\x15\n\rreq_bandwidth\x18\x03 \x01(\x05\"o\n\nTunnelResp\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x11\n\ttunnel_id\x18\x02 \x01(\r\x12\x14\n\x0c\x66irst_hop_ip\x18\x03 \x01(\t\x12\x16\n\x0e\x66irst_hop_port\x18\x04 \x01(\x05\x12\x0f\n\x07message\x18\x05 \x01(\t2=\n\x0f\x44irectoryServer\x12*\n\rRequestTunnel\x12\n.TunnelReq\x1a\x0b.TunnelResp\"\x00\x62\x06proto3')



_TUNNELREQ = DESCRIPTOR.message_types_by_name['TunnelReq']
_TUNNELRESP = DESCRIPTOR.message_types_by_name['TunnelResp']
TunnelReq = _reflection.GeneratedProtocolMessageType('TunnelReq', (_message.Message,), {
  'DESCRIPTOR' : _TUNNELREQ,
  '__module__' : 'control_pb2'
  # @@protoc_insertion_point(class_scope:TunnelReq)
  })
_sym_db.RegisterMessage(TunnelReq)

TunnelResp = _reflection.GeneratedProtocolMessageType('TunnelResp', (_message.Message,), {
  'DESCRIPTOR' : _TUNNELRESP,
  '__module__' : 'control_pb2'
  # @@protoc_insertion_point(class_scope:TunnelResp)
  })
_sym_db.RegisterMessage(TunnelResp)

_DIRECTORYSERVER = DESCRIPTOR.services_by_name['DirectoryServer']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TUNNELREQ._serialized_start=17
  _TUNNELREQ._serialized_end=90
  _TUNNELRESP._serialized_start=92
  _TUNNELRESP._serialized_end=203
  _DIRECTORYSERVER._serialized_start=205
  _DIRECTORYSERVER._serialized_end=266
# @@protoc_insertion_point(module_scope)
